Updates README files
xmos/lib_i2c pull request #64
Opened 2020-12-02 09:57 UTC by lucianomartin

The list of guidelines can be found in https://xmosjira.atlassian.net/wiki/spaces/PR/pages/2197749954/Read+Me+File+Guidelines

2020-12-02 11:03 UTC, mbanth requested changes
One small change.

2020-12-02 11:03 UTC, mbanth commented on README.rst
> +For a list of direct dependencies, look for DEPENDENT_MODULES in lib_xxx/module_build_info.
Replace` lib_xxx` with `lib_i2c`

2020-12-02 11:17 UTC, lucianomartin commented on README.rst
> +For a list of direct dependencies, look for DEPENDENT_MODULES in lib_xxx/module_build_info.
Fixed. Thanks for spotting it.

2020-12-02 11:23 UTC, mbanth approved these changes
Looks good.

2020-12-10 14:50 UTC, lucianomartin commented
This PR has been replaced by https://github.com/xmos/lib_i2c/pull/65

2020-12-10 14:50 UTC, closed without merging